#!/usr/bin/env python3
"""Tests for prune-comments/scripts/git-checkpoint.py.

Run with: python3 tests/test_git_checkpoint.py
Stdlib-only. Each test runs in a throwaway repo with an isolated HOME.
"""
import importlib.util as _ilu
import os
import stat
import subprocess
import tempfile
import unittest
from unittest.mock import patch

HERE = os.path.dirname(os.path.abspath(__file__))
SCRIPT = os.path.join(os.path.dirname(HERE), "scripts", "git-checkpoint.py")
_spec = _ilu.spec_from_file_location("git_checkpoint", SCRIPT)
gc = _ilu.module_from_spec(_spec)
_spec.loader.exec_module(gc)

AUTHOR = ["-c", "user.name=t", "-c", "user.email=t@t"]


class RepoCase(unittest.TestCase):
    def setUp(self):
        self._tmp = tempfile.TemporaryDirectory()
        self.repo = os.path.join(self._tmp.name, "repo")
        os.makedirs(self.repo)
        home = os.path.join(self._tmp.name, "home")
        os.makedirs(home)
        env = {"HOME": home, "GIT_CONFIG_NOSYSTEM": "1", "XDG_CONFIG_HOME": home}
        self._env = patch.dict(os.environ, env)
        self._env.start()
        self.git("init", "-q", "-b", "main")

    def tearDown(self):
        self._env.stop()
        self._tmp.cleanup()

    def git(self, *args):
        return subprocess.run(
            ["git", *args], cwd=self.repo, capture_output=True, text=True, check=True
        ).stdout

    def write(self, path, text):
        full = os.path.join(self.repo, path)
        os.makedirs(os.path.dirname(full), exist_ok=True)
        with open(full, "w", encoding="utf-8") as fh:
            fh.write(text)

    def read(self, path):
        with open(os.path.join(self.repo, path), encoding="utf-8") as fh:
            return fh.read()

    def commit_all(self, msg="init"):
        self.git("add", "-A")
        self.git(*AUTHOR, "commit", "-q", "-m", msg)

    def run_cp(self, *argv):
        return gc.run(list(argv), cwd=self.repo)

    def seed(self):
        self.write("a.py", "# Step 1: init\nx = 1\n# Step 2: done\ny = 2\n")
        self.commit_all()


class TestBeginGuards(RepoCase):
    def test_no_commits(self):
        self.write("a.py", "x = 1\n")
        code, out = self.run_cp("begin")
        self.assertEqual((code, out["error"]), (1, "no-commits"))

    def test_not_a_repo(self):
        code, out = gc.run(["begin"], cwd=self._tmp.name)
        self.assertEqual((code, out["error"]), (1, "not-a-repo"))

    def test_clean_tree_without_full(self):
        self.seed()
        code, out = self.run_cp("begin")
        self.assertEqual((code, out["error"]), (2, "no-changes"))

    def test_merge_in_progress(self):
        self.seed()
        self.write("a.py", "changed\n")
        head = self.git("rev-parse", "HEAD").strip()
        with open(os.path.join(self.repo, ".git", "MERGE_HEAD"), "w") as fh:
            fh.write(head + "\n")
        code, out = self.run_cp("begin")
        self.assertEqual((code, out["error"]), (1, "operation-in-progress"))

    def test_pending_checkpoint_blocks_second_begin(self):
        self.seed()
        self.write("a.py", "changed\n")
        self.assertEqual(self.run_cp("begin")[0], 0)
        self.write("a.py", "changed again\n")
        code, out = self.run_cp("begin")
        self.assertEqual((code, out["error"]), (1, "pending-checkpoint"))

    def test_usage(self):
        self.assertEqual(self.run_cp("nope")[1]["error"], "usage")


class TestBeginCheckpoint(RepoCase):
    def test_hooks_and_signing_do_not_block(self):
        self.seed()
        hook = os.path.join(self.repo, ".git", "hooks", "pre-commit")
        with open(hook, "w") as fh:
            fh.write("#!/bin/sh\nexit 1\n")
        os.chmod(hook, os.stat(hook).st_mode | stat.S_IEXEC)
        self.git("config", "commit.gpgsign", "true")
        self.git("config", "gpg.program", "false")
        self.write("a.py", "changed\n")
        code, out = self.run_cp("begin")
        self.assertEqual(code, 0, out)
        self.assertEqual(self.git("log", "-1", "--format=%s").strip(), gc.MARKER)

    def test_scope_includes_untracked_and_skips_ignored(self):
        self.seed()
        self.write("a.py", "# changed\nx = 1\n")
        self.write("new.ts", "// Step 1\nconst a = 1\n")
        self.write("dist/out.js", "// built\n")
        self.write("lib/app.min.js", "x\n")
        self.write("gen.go", "// Code generated by tool. DO NOT EDIT.\npackage x\n")
        self.write("package-lock.json", "{}\n")
        code, out = self.run_cp("begin")
        self.assertEqual(code, 0, out)
        self.assertEqual(sorted(out["scope"]), ["a.py", "new.ts"])
        self.assertEqual(out["skipped"], 4)

    def test_deleted_files_not_in_scope(self):
        self.write("b.py", "z = 3\n")
        self.seed()
        os.remove(os.path.join(self.repo, "b.py"))
        self.write("a.py", "changed\n")
        self.assertEqual(self.run_cp("begin")[1]["scope"], ["a.py"])

    def test_full_on_clean_tree_creates_no_commit(self):
        self.seed()
        head = self.git("rev-parse", "HEAD").strip()
        code, out = self.run_cp("begin", "--full")
        self.assertEqual((code, out["mode"], out["scope"]), (0, "clean", ["a.py"]))
        self.assertEqual(self.git("rev-parse", "HEAD").strip(), head)


class TestAcceptReject(RepoCase):
    def setup_partial_staging(self):
        self.seed()
        self.write("a.py", "# Step 1: init\nx = 10\n# Step 2: done\ny = 2\n")
        self.git("add", "a.py")
        self.write("a.py", "# Step 1: init\nx = 10\n# Step 2: done\ny = 20\n")
        self.write("new.py", "# Helper function\ndef f(): pass\n")
        self.orig_index = self.git("write-tree").strip()
        self.orig_status = self.git("status", "--porcelain")
        self.orig_a = self.read("a.py")
        self.orig_new = self.read("new.py")
        self.head = self.git("rev-parse", "HEAD").strip()

    def prune(self):
        self.write("a.py", "x = 10\ny = 20\n")
        self.write("new.py", "def f(): pass\n")

    def test_accept_keeps_edits_and_restores_index(self):
        self.setup_partial_staging()
        self.assertEqual(self.run_cp("begin")[0], 0)
        self.prune()
        code, out = self.run_cp("accept")
        self.assertEqual(code, 0, out)
        self.assertEqual(sorted(out["accepted"]), ["a.py", "new.py"])
        self.assertEqual(self.git("rev-parse", "HEAD").strip(), self.head)
        self.assertEqual(self.git("write-tree").strip(), self.orig_index)
        self.assertEqual(self.read("a.py"), "x = 10\ny = 20\n")
        self.assertIn("?? new.py", self.git("status", "--porcelain"))
        self.assertEqual(self.run_cp("status")[1]["pending"], False)

    def test_reject_restores_everything(self):
        self.setup_partial_staging()
        self.run_cp("begin")
        self.prune()
        code, out = self.run_cp("reject")
        self.assertEqual(code, 0, out)
        self.assertEqual(sorted(out["restored"]), ["a.py", "new.py"])
        self.assertEqual(self.read("a.py"), self.orig_a)
        self.assertEqual(self.read("new.py"), self.orig_new)
        self.assertEqual(self.git("rev-parse", "HEAD").strip(), self.head)
        self.assertEqual(self.git("write-tree").strip(), self.orig_index)
        self.assertEqual(self.git("status", "--porcelain"), self.orig_status)
        self.assertNotIn(gc.MARKER, self.git("log", "--format=%s"))

    def test_reject_leaves_out_of_scope_edits(self):
        self.seed()
        self.write("a.py", "changed\n")
        self.write("dist/x.js", "built\n")
        self.git("add", "-f", "dist/x.js")
        self.git(*AUTHOR, "commit", "-q", "-m", "track dist")
        self.write("a.py", "changed again\n")
        self.run_cp("begin")
        self.write("a.py", "pruned\n")
        self.write("dist/x.js", "user edit\n")
        _, out = self.run_cp("reject")
        self.assertEqual(out["restored"], ["a.py"])
        self.assertEqual(out["outside_scope_untouched"], ["dist/x.js"])
        self.assertEqual(self.read("dist/x.js"), "user edit\n")

    def test_full_clean_reject(self):
        self.seed()
        self.run_cp("begin", "--full")
        self.write("a.py", "x = 1\ny = 2\n")
        _, out = self.run_cp("reject")
        self.assertEqual(out["restored"], ["a.py"])
        self.assertEqual(self.git("status", "--porcelain"), "")

    def test_head_moved_guard(self):
        self.seed()
        self.write("a.py", "changed\n")
        self.run_cp("begin")
        self.write("b.py", "other\n")
        self.git("add", "b.py")
        self.git(*AUTHOR, "commit", "-q", "-m", "user commit")
        head = self.git("rev-parse", "HEAD").strip()
        for cmd in ("accept", "reject"):
            code, out = self.run_cp(cmd)
            self.assertEqual((code, out["error"]), (1, "head-moved"))
        self.assertEqual(self.git("rev-parse", "HEAD").strip(), head)

    def test_accept_without_begin(self):
        self.seed()
        self.assertEqual(self.run_cp("accept")[1]["error"], "no-checkpoint")


class TestStatus(RepoCase):
    def test_pending_state(self):
        self.seed()
        self.write("a.py", "changed\n")
        self.run_cp("begin")
        _, out = self.run_cp("status")
        self.assertEqual((out["pending"], out["orphan"]), (True, False))

    def test_orphan_marker_commit(self):
        self.seed()
        self.write("a.py", "changed\n")
        self.run_cp("begin")
        os.remove(os.path.join(self.repo, ".git", gc.STATE_NAME))
        _, out = self.run_cp("status")
        self.assertEqual((out["pending"], out["orphan"]), (True, True))

    def test_nothing_pending(self):
        self.seed()
        self.assertEqual(self.run_cp("status")[1], {"pending": False})


if __name__ == "__main__":
    unittest.main(verbosity=2)
